### ISSUE TITLE
Обновите до 5.5

### ISSUE THREAD

**Issue by ghost** [SpeakingFish/attendant#1]
Доброго времени суток.

Заметил при подборе удобного логгера, что ваш программный код устарел. Как будет возможность — обновите.

**Comment by SpeakingFish** [comment]
Добрый день.
Мне до сих пор не было необходимости в новых версиях Qt.
Если вам это необходимо, я могу обновить до новой версии. Так же если будут пожелания, то присылайте предложения - у меня найдется несколько часов на этой неделе заняться этим проектом.

**Comment by ghost** [comment]
@SpeakingFish пока пожеланий нет, я использую логгер со статической линковкой, да и думаю, что в будущем слезу на нижние версии qt по зову разума :)
